# 必须是字符串
version: '3.8'

services: 
    cwy516project: 
        image: cwy516project:v1
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "5100:80"
        depends_on: 
            - consul1
            - consul2
            - consul3
            - consul4
            - nginx
            - redis
            - rabbitmq1
            - rabbitmq2
            - rabbitmq3
    consul1: 
        image: consul:latest
        container_name: consul1
        restart: always
        ports: 
            - "8500:8500"
            - "53"
        hostname: "consul-server1"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server1 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1
        volumes: 
            - /usr/consul/consul1:/consul/data
    consul2: 
        image: consul:latest
        container_name: consul2
        restart: always
        ports: 
            - "8501:8500"
            - "53"
        hostname: "consul-server2"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server2 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1 -retry-join=consul-server1
        volumes: 
            - /usr/consul/consul2:/consul/data
        depends_on: 
            - consul1
    consul3: 
        image: consul:latest
        container_name: consul3
        restart: always
        ports: 
            - "8502:8500"
            - "53"
        hostname: "consul-server3"
        command: agent -server -ui -bootstrap-expect=3 -node=consul-server3 -disable-host-node-id -client=0.0.0.0 -bind=0.0.0.0 -datacenter=dc1 -retry-join=consul-server1
        volumes: 
            - /usr/consul/consul3:/consul/data
        depends_on: 
            - consul1
    consul4: 
        image: consul:latest
        container_name: consul4
        restart: always
        ports: 
            - "8503:8500"
            - "53"
        hostname: "consul-client"
        command: agent -ui -node=consul-client -client=0.0.0.0 -bind=0.0.0.0 -disable-host-node-id -datacenter=dc1 -retry-join=consul-server1
        volumes: 
            - /usr/consul/consul4:/consul/data
        depends_on: 
            - consul1
    nginx: 
        image: 192.168.123.185/test/nginx:v1
        container_name: nginx
        restart: always
        ports: 
            - "8090:8090"
        volumes: 
            - /home/cwy/webroot/cwy516project/nginx/nginx.conf:/etc/nginx/nginx.conf
    redis: 
        image: 192.168.123.185/test/redis:v1
        container_name: redis
        restart: always
        ports: 
            - "6379:6379"
        command: redis-server /etc/redis/redis.conf
        volumes: 
            - /home/cwy/webroot/cwy516project/redis/redis.conf:/etc/redis/redis.conf
            - /home/cwy/webroot/cwy516project/redis/data:/data
    rabbitmq1: 
        image: rabbitmq:3.8-management
        container_name: rabbitmq1
        restart: always
        hostname: rabbit1
        ports: 
            - 5672:5672
            - 15672:15672
        environment: 
            - RABBITMQ_ERLANG_COOKIE=mycookie
    rabbitmq2: 
        image: rabbitmq:3.8-management
        container_name: rabbitmq2
        restart: always
        hostname: rabbit2
        ports: 
            - 5673:5672
            - 15673:15672
        environment: 
            - RABBITMQ_ERLANG_COOKIE=mycookie
        links: 
            - rabbitmq1
    rabbitmq3:
        image: rabbitmq:3.8-management
        container_name: rabbitmq3
        restart: always
        hostname: rabbit3
        ports: 
            - 5674:5672
            - 15674:15672
        environment: 
            - RABBITMQ_ERLANG_COOKIE=mycookie
        links: 
            - rabbitmq1
            - rabbitmq2
    rabbitmqnew1: 
        image: rabbitmq:management
        container_name: rabbitmqnew1
        restart: always
        hostname: rabbitnew1
        ports: 
            - 5675:5672
            - 15675:15672
        volumes: 
            - /home/cwy/webroot/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    rabbitmqnew2: 
        image: rabbitmq:management
        container_name: rabbitmqnew2
        restart: always
        hostname: rabbitnew2
        ports: 
            - 5676:5672
            - 15676:15672
        volumes: 
            - /home/cwy/webroot/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
        links: 
            - rabbitmqnew1
    rabbitmqnew3: 
        image: rabbitmq:management
        container_name: rabbitmqnew3
        restart: always
        hostname: rabbitnew3
        ports: 
            - 5677:5672
            - 15677:15672
        volumes: 
            - /home/cwy/webroot/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
        links: 
            - rabbitmqnew1
            - rabbitmqnew2


