version: '3'
services: 
  consul-server1: 
    image: consul:latest
    hostname: "consul-server1"
    container_name: consul1
    ports: 
      - "8500:8500"
      - "53"
    volumes: 
      - /usr/consul/consul1:/consul/data
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
  consul-server2: 
    image: consul:latest
    hostname: "consul-server2"
    container_name: consul2
    ports: 
      - "8501:8500"
      - "53"
    volumes: 
      - /usr/consul/consul2:/consul/data
    command: "agent -server -ui -join consul-server1 -disable-host-node-id -client 0.0.0.0"
    depends_on: 
      - consul-server1
  consul-server3: 
    image: consul:latest
    hostname: "consul-server3"
    container_name: consul3
    ports: 
      - "8502:8500"
      - "53"
    volumes: 
      - /usr/consul/consul3:/consul/data
    command: "agent -server -ui -join consul-server1 -disable-host-node-id -client 0.0.0.0"
    depends_on: 
      - consul-server1
  consul-node1: 
    image: consul:latest
    hostname: "consul-node1"
    container_name: consul4
    ports: 
      - "8503:8500"
      - "53"
    command: "agent -join consul-server1 -disable-host-node-id"
    depends_on: 
      - consul-server1